using System.Text;

namespace Tauri.Plugin.DotNet.Generator;

static class CodeEmitter
{
    internal const string ToolName = "BindingGenerator";
    internal const string GeneratedHeader = "// Auto-generated by " + ToolName + ". Do not edit.";

    internal static string GenerateServiceFile(ServiceDef service, Dictionary<string, TypeDef> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine("import { call } from \"./runtime\";");

        // Check if any method references a model type
        var usesModels = service.Methods
            .Any(m => ReferencesModel(m.ReturnType, models) ||
                       m.Parameters.Any(p => ReferencesModel(p.Type, models)));
        if (usesModels)
        {
            var modelNames = GetReferencedModelNames(service, models);
            if (modelNames.Count > 0)
            {
                sb.AppendLine($"import type {{ {string.Join(", ", modelNames)} }} from \"./models\";");
            }
        }

        sb.AppendLine();

        foreach (var method in service.Methods)
        {
            var returnTs = ReturnTsType(method, models);
            var isVoid = returnTs == "void";

            // Parameter list
            var paramList = ParameterList(method, models);

            var tsReturn = $"Promise<{returnTs}>";

            sb.AppendLine($"export function {method.Name}({paramList}): {tsReturn} {{");

            // Arguments to pass
            var argList = string.Join(", ",
                method.Parameters.Select(p => StringHelpers.ToCamelCase(p.Name)));

            var callArgs = string.IsNullOrEmpty(argList)
                ? $"\"{service.Name}.{method.Name}\""
                : $"\"{service.Name}.{method.Name}\", {argList}";

            if (isVoid)
                sb.AppendLine($"  return call<void>({callArgs});");
            else
                sb.AppendLine($"  return call<{returnTs}>({callArgs});");

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    /// <summary>The TypeScript result type of a method: "void" for no result, and "| null" when C# declares it nullable.</summary>
    private static string ReturnTsType(MethodDef method, Dictionary<string, TypeDef> models)
    {
        var returnTs = TypeMapper.MapTypeToTS(method.ReturnType, models);
        var isVoid = returnTs == "void" ||
                     (TypeMapper.IsTaskType(method.ReturnType) && !method.ReturnType.IsGenericType);
        return isVoid ? "void" : WithNull(returnTs, method.ReturnIsNullable);
    }

    private static string ParameterList(MethodDef method, Dictionary<string, TypeDef> models) =>
        string.Join(", ", method.Parameters.Select(p =>
            $"{StringHelpers.ToCamelCase(p.Name)}: {WithNull(TypeMapper.MapTypeToTS(p.Type, models), p.IsNullable)}"));

    private static string WithNull(string tsType, bool nullable) =>
        nullable && !tsType.EndsWith(" | null", StringComparison.Ordinal) ? $"{tsType} | null" : tsType;

    /// <summary>
    /// Generates the TypeScript side of the [BridgeFrontend] interfaces: a typed interface for each,
    /// and an <c>implement…</c> function that registers an implementation with the runtime so .NET can call it.
    /// </summary>
    internal static string GenerateFrontendsFile(List<FrontendDef> frontends, Dictionary<string, TypeDef> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine("import { registerFrontend } from \"./runtime\";");

        var modelNames = GetReferencedModelNames(frontends.SelectMany(f => f.Methods), models);
        if (modelNames.Count > 0)
            sb.AppendLine($"import type {{ {string.Join(", ", modelNames)} }} from \"./models\";");

        sb.AppendLine();

        foreach (var frontend in frontends)
        {
            sb.AppendLine("/**");
            sb.AppendLine($" * What .NET can ask this window to do (the C# `{frontend.InterfaceName}` interface).");
            sb.AppendLine(" */");
            sb.AppendLine($"export interface {frontend.InterfaceName} {{");
            foreach (var method in frontend.Methods)
                sb.AppendLine($"  {method.Name}({ParameterList(method, models)}): Promise<{ReturnTsType(method, models)}>;");
            sb.AppendLine("}");
            sb.AppendLine();

            sb.AppendLine("/**");
            sb.AppendLine($" * Registers this window's implementation of `{frontend.InterfaceName}`. Call it once at startup:");
            sb.AppendLine(" * a request that reaches the window before that is not replayed. An error thrown by a method");
            sb.AppendLine(" * is sent back to .NET as a `FrontendException`.");
            sb.AppendLine(" * @returns A function that removes the implementation.");
            sb.AppendLine(" */");
            sb.AppendLine($"export function implement{StringHelpers.ToPascalCase(frontend.Name)}(implementation: {frontend.InterfaceName}): () => void {{");
            sb.AppendLine($"  return registerFrontend(\"{frontend.Name}\", implementation);");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    internal static string GenerateModelsFile(Dictionary<string, TypeDef> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine();

        foreach (var model in models.Values)
        {
            if (model.Kind == TypeDefKind.Enum && model.IsFlags)
            {
                // A [Flags] enum written by JsonStringEnumConverter: "Read, Write". No enum or union can say that.
                sb.AppendLine($"// A [Flags] enum, written as its member names joined with \", \" (for example \"{FlagsExample(model)}\").");
                sb.AppendLine($"export type {model.Name} = string;");
            }
            else if (model.Kind == TypeDefKind.Enum)
            {
                sb.AppendLine($"export enum {model.Name} {{");
                foreach (var val in model.EnumValues!)
                {
                    sb.AppendLine($"  {val.Name} = {StringHelpers.FormatEnumValue(val.Value)},");
                }
                sb.AppendLine("}");
            }
            else
            {
                var extendsClause = model.BaseTypeName != null ? $" extends {model.BaseTypeName}" : "";
                var typeParameters = model.GenericParameters is { Count: > 0 } ? $"<{string.Join(", ", model.GenericParameters)}>" : "";
                sb.AppendLine($"export interface {model.Name}{typeParameters}{extendsClause} {{");
                foreach (var prop in model.Properties!)
                {
                    var tsType = TypeMapper.MapTypeToTS(prop.Type, models, prop.NumbersAsString, prop.Converter);

                    // Use [JsonPropertyName] value if present, otherwise camelCase the C# name
                    var propName = prop.JsonName ?? StringHelpers.ToCamelCase(prop.Name);

                    // Check if nullable (Nullable<T> for value types, NRT for reference types)
                    var isNullableValue = prop.Type.IsGenericType &&
                        prop.Type.GetGenericTypeDefinition().FullName == typeof(Nullable<>).FullName;
                    var isOptional = isNullableValue || prop.IsNullableRef;

                    if (isOptional)
                    {
                        // Remove " | null" if already in the mapped type (from Nullable<T>)
                        tsType = tsType.Replace(" | null", "");
                        sb.AppendLine($"  {propName}?: {tsType};");
                    }
                    else
                    {
                        sb.AppendLine($"  {propName}: {tsType};");
                    }
                }
                sb.AppendLine("}");
            }

            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string FlagsExample(TypeDef model) =>
        string.Join(", ", model.EnumValues!.Where(v => !Equals(v.Name, "None")).Select(v => v.Name).Take(2));

    internal static string GenerateEventsFile(List<EventDef> events, Dictionary<string, TypeDef> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);
        sb.AppendLine("import { on, once, off, type EventCallback } from \"./runtime\";");

        // Import referenced model types
        var modelNames = new HashSet<string>();
        foreach (var evt in events)
        {
            if (TryGetModel(evt.PayloadType, models, out var m))
                modelNames.Add(m.Name);
        }
        if (modelNames.Count > 0)
        {
            sb.AppendLine($"import type {{ {string.Join(", ", modelNames)} }} from \"./models\";");
        }

        sb.AppendLine();

        foreach (var evt in events)
        {
            var tsType = TypeMapper.MapTypeToTS(evt.PayloadType, models);
            var fnName = StringHelpers.ToPascalCase(evt.Name);

            // on<Type>("name", cb) wrapper
            sb.AppendLine($"/**");
            sb.AppendLine($" * Subscribe to the \"{evt.Name}\" event.");
            sb.AppendLine($" * @returns A dispose function that removes this listener.");
            sb.AppendLine($" */");
            sb.AppendLine($"export function on{fnName}(callback: EventCallback<{tsType}>): () => void {{");
            sb.AppendLine($"  return on<{tsType}>(\"{evt.Name}\", callback);");
            sb.AppendLine("}");
            sb.AppendLine();

            // once<Type>("name", cb) wrapper
            sb.AppendLine($"/**");
            sb.AppendLine($" * Subscribe to the \"{evt.Name}\" event for a single occurrence.");
            sb.AppendLine($" * @returns A dispose function that removes this listener.");
            sb.AppendLine($" */");
            sb.AppendLine($"export function once{fnName}(callback: EventCallback<{tsType}>): () => void {{");
            sb.AppendLine($"  return once<{tsType}>(\"{evt.Name}\", callback);");
            sb.AppendLine("}");
            sb.AppendLine();

            // off<Type>("name", cb) wrapper
            sb.AppendLine($"/**");
            sb.AppendLine($" * Unsubscribe a callback from the \"{evt.Name}\" event.");
            sb.AppendLine($" */");
            sb.AppendLine($"export function off{fnName}(callback: EventCallback<{tsType}>): void {{");
            sb.AppendLine($"  off<{tsType}>(\"{evt.Name}\", callback);");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    internal static string GenerateIndexFile(
        List<ServiceDef> services, List<EventDef> events, Dictionary<string, TypeDef> models, List<FrontendDef>? frontends = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine(GeneratedHeader);

        foreach (var svc in services)
        {
            sb.AppendLine($"export * as {svc.Name} from \"./{svc.Name}\";");
        }

        if (models.Count > 0)
        {
            sb.AppendLine("export * from \"./models\";");
        }

        if (events.Count > 0)
        {
            sb.AppendLine("export * from \"./events\";");
        }

        if (frontends is { Count: > 0 })
        {
            sb.AppendLine("export * from \"./frontends\";");
        }

        return sb.ToString();
    }

    /// <summary>The model a type stands for: the type itself, or the definition of a generic instantiation.</summary>
    private static bool TryGetModel(Type type, Dictionary<string, TypeDef> models, out TypeDef model)
    {
        var key = type.IsGenericType ? type.GetGenericTypeDefinition().FullName : type.FullName;
        if (key != null && models.TryGetValue(key, out var found))
        {
            model = found;
            return true;
        }
        model = null!;
        return false;
    }

    internal static bool ReferencesModel(Type type, Dictionary<string, TypeDef> models)
    {
        if (TryGetModel(type, models, out _)) return true;
        if (type.IsArray) return ReferencesModel(type.GetElementType()!, models);
        if (type.IsGenericType)
            return type.GetGenericArguments().Any(a => ReferencesModel(a, models));
        return false;
    }

    internal static HashSet<string> GetReferencedModelNames(ServiceDef service, Dictionary<string, TypeDef> models) =>
        GetReferencedModelNames(service.Methods, models);

    internal static HashSet<string> GetReferencedModelNames(IEnumerable<MethodDef> methods, Dictionary<string, TypeDef> models)
    {
        var names = new HashSet<string>();

        void Collect(Type type)
        {
            if (TryGetModel(type, models, out var m))
                names.Add(m.Name);
            if (type.IsArray) Collect(type.GetElementType()!);
            if (type.IsGenericType)
                foreach (var a in type.GetGenericArguments())
                    Collect(a);
        }

        foreach (var method in methods)
        {
            Collect(method.ReturnType);
            foreach (var p in method.Parameters)
                Collect(p.Type);
        }

        return names;
    }
}
